# Generated by Django 4.2.7 on 2023-11-28 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendordetails",
            name="id",
        ),
        migrations.AlterField(
            model_name="vendordetails",
            name="vendor_code",
            field=models.CharField(
                db_index=True,
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="purchaseOrderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=200, unique=True)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateTimeField()),
                ("items", models.JSONField()),
                ("quantity", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
                ("quality_rating", models.FloatField(null=True)),
                ("issue_date", models.DateTimeField(null=True)),
                ("acknowledgment_date", models.DateTimeField(null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        db_column="vendor_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vendors.vendordetails",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_orders",
            },
        ),
    ]
